"""empty message

Revision ID: 3937f4d03379
Revises: 0e0b131604ee
Create Date: 2020-06-26 14:18:46.588966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3937f4d03379'
down_revision = '0e0b131604ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('user_email', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'user_email')
    # ### end Alembic commands ###
