"""empty message

Revision ID: 71a6b2b3c126
Revises: cdfa3a1d33a0
Create Date: 2020-06-22 20:05:07.645070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a6b2b3c126'
down_revision = 'cdfa3a1d33a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'product', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    # ### end Alembic commands ###
